name: binlist_flutter
description: An open-source list of bank BIN/IIN numbers.
version: 0.0.1
homepage: https://github.com/xonaman/binlist_flutter

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0